<?php

namespace Proxies\__CG__\MaisonLigues\croisiereBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Categorie extends \MaisonLigues\croisiereBundle\Entity\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setLettre($lettre)
    {
        $this->__load();
        return parent::setLettre($lettre);
    }

    public function getLettre()
    {
        $this->__load();
        return parent::getLettre();
    }

    public function setLibelle($libelle)
    {
        $this->__load();
        return parent::setLibelle($libelle);
    }

    public function getLibelle()
    {
        $this->__load();
        return parent::getLibelle();
    }

    public function addLeContenant(\MaisonLigues\croisiereBundle\Entity\Contenir $leContenant)
    {
        $this->__load();
        return parent::addLeContenant($leContenant);
    }

    public function removeLeContenant(\MaisonLigues\croisiereBundle\Entity\Contenir $leContenant)
    {
        $this->__load();
        return parent::removeLeContenant($leContenant);
    }

    public function getLeContenant()
    {
        $this->__load();
        return parent::getLeContenant();
    }

    public function setLesTypes(\MaisonLigues\croisiereBundle\Entity\Type $lesTypes = NULL)
    {
        $this->__load();
        return parent::setLesTypes($lesTypes);
    }

    public function getLesTypes()
    {
        $this->__load();
        return parent::getLesTypes();
    }

    public function addLesType(\MaisonLigues\croisiereBundle\Entity\Type $lesTypes)
    {
        $this->__load();
        return parent::addLesType($lesTypes);
    }

    public function removeLesType(\MaisonLigues\croisiereBundle\Entity\Type $lesTypes)
    {
        $this->__load();
        return parent::removeLesType($lesTypes);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'lettre', 'libelle', 'leContenant', 'lesTypes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}