<?php

namespace MaisonLigues\croisiereBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnregistrerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnregistrerRepository extends EntityRepository
{
}
